<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="description" content="Lab 08 PHP Sessions Activity" />
    <meta name="keywords" content="PHP, sessions, includes, hidden fields" />
    <meta name="author" content="Ruby" />
    <title><?php echo $pageTitle; ?></title>
  </head>

  <body>
    <header>
      <h1>Lab 08 Login System</h1>
    </header>
  </body>
</html>
